#------------------------------------------------------------
# spock-doc
#------------------------------------------------------------
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spock-doc
  namespace: {{.Namespace}}
  labels:
    s-product: {{.Product}}
    s-group: {{.Group}}
    s-service: {{.Service}}
spec:
  rules:
  - host: {{.Service}}-{{.Namespace}}.ke-cs.dev.qiniu.io
    http:
      paths:
      - backend:
          serviceName: spock-doc
          servicePort: 80
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: spock-doc
  namespace: {{.Namespace}}
  labels:
    s-product: {{.Product}}
    s-group: {{.Group}}
    s-service: {{.Service}}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    s-product: {{.Product}}
    s-group: {{.Group}}
    s-service: {{.Service}}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spock-doc
  namespace: {{.Namespace}}
  labels:
    s-product: {{.Product}}
    s-group: {{.Group}}
    s-service: {{.Service}}
spec:
  replicas: 1
  selector:
    matchLabels:
      s-product: {{.Product}}
      s-group: {{.Group}}
      s-service: {{.Service}}
  template:
    metadata:
      labels:
        s-product: {{.Product}}
        s-group: {{.Group}}
        s-service: {{.Service}}
    spec:
      imagePullSecrets:
        - name: qn-registry-secret
      containers:
        - image: "index.qiniu.com/spocktest/spock-doc:latest"
          imagePullPolicy: Always
          name: spock-doc
          ports:
            - protocol: TCP
              containerPort: 80